#!/bin/sh
SCRIPT=$(readlink $0 || true)
if [ -z $SCRIPT ]; then
    SCRIPT=$0
fi
SCRIPT_DIR="$(cd $(dirname "$SCRIPT") && pwd -P)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd -P)"
if [ -z $BUMBLEBEE_LNS_HOME ]; then
    BUMBLEBEE_LNS_HOME=$ROOT_DIR
fi

cd $BUMBLEBEE_LNS_HOME && erl -noinput +Bd -sname loractl -pa $ROOT_DIR/lib/*/ebin -s bumblebee_control $@ -s init stop
