defmodule BumblebeeLnsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :bumblebee_lns

  @session_options [
    store: :cookie,
    key: "_bumblebee_lns_key",
    signing_salt: "bumblebee-session",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :bumblebee_lns,
    gzip: not code_reloading?,
    only: BumblebeeLnsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  # plug Phoenix.LiveDashboard.RequestLogger,
  #   param_key: "request_logger",
  #   cookie_key: "request_logger"
  # plug Plug.Static,
  #   at: "/assets/phoenix",
  #   from: {:phoenix, "priv/static"},
  #   only: ~w(phoenix.min.js)

  # plug Plug.Static,
  #   at: "/assets/live_view",
  #   from: {:phoenix_live_view, "priv/static"},
  #   only: ~w(phoenix_live_view.min.js)

  # plug Plug.Static,
  #   at: "/assets/backpex",
  #   from: {:backpex, "priv/static/js"},
  #   only: ~w(backpex.esm.js)

  # plug Plug.Static,
  #   at: "/assets",
  #   from: {:bumblebee_lns, "priv/static/assets"},
  #   only: ~w(app.css)

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  plug Plug.Parsers, parsers: [:urlencoded, :multipart, :json], pass: ["*/*"], json_decoder: Jason
  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BumblebeeLnsWeb.Router
end
